#!/bin/sh

CWD=`pwd`
PROGNAME="setup-environment"

usage()
{   
    echo -e "
Usage:	source $PROGNAME <build-dir>
	<build-dir>  build directory

The first usage is for creating a new build directory. In this case, the
script creates the build directory <build-dir>, and prepares the calling 
shell for running bitbake on the build directory.

The second usage is for using an existing build directory. In this case,
the script prepares the calling shell for running bitbake on the build
directory <build-dir>. The build directory configuration is unchanged.
"
}

clean_up()
{  
   unset CWD PROGNAME OEROOT
}

if [ "$(whoami)" = "root" ]; then
    echo "ERROR: Do not use the BSP as root. Exiting..."
fi

if [ ! -e $1/conf/local.conf ]; then
    echo -e "ERROR: You must create /conf/local.conf file."
    clean_up
    return 1
fi

OEROOT=$PWD/sources/poky

. $OEROOT/oe-init-build-env $CWD/$1 > /dev/null

# Clean up PATH, because if it includes tokens to current directories somehow,
# wrong binaries can be used instead of the expected ones during task execution
export PATH="`echo $PATH | sed 's/\(:.\|:\)*:/:/g;s/^.\?://;s/:.\?$//'`"

clean_up
